// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateModels(arg1) {
  return window['go']['main']['App']['GenerateModels'](arg1);
}

export function OpenJSONFile() {
  return window['go']['main']['App']['OpenJSONFile']();
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2);
}

export function ValidateJSON(arg1) {
  return window['go']['main']['App']['ValidateJSON'](arg1);
}
