// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GenerateModels(arg1:main.GenerateRequest):Promise<main.GenerateResponse>;

export function OpenJSONFile():Promise<main.OpenFileResult>;

export function SaveTextFile(arg1:string,arg2:string):Promise<main.SaveFileResult>;

export function ValidateJSON(arg1:string):Promise<main.ValidationResult>;
